Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2024-10, with the labels that each got.

#70 Fix/notification
  src/@types/Notification.d.ts
  src/components/common/route/PublicRoute.tsx
  src/components/layout/GlobalLayout.tsx
  src/components/layout/RealTimeNotification.tsx
  src/components/login/queries.ts
  src/components/notification/NotificationItem.tsx
  src/components/notification/queries.ts
  src/hooks/useSSE.ts
  src/mocks/data/notificationData.ts
  src/mocks/handlers/notification.ts
  src/pages/Notification.tsx
  src/pages/ProductList.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#77 Fix. 상세 페이지 router 수정
  src/components/details/AuctionItem.tsx
  src/components/details/ProgressBar.tsx
  src/pages/AuctionDetail.tsx
  src/pages/PreAuction.tsx
  src/router.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#83 Test / bid flow
  src/components/bid/BidFooter.tsx
  src/constants/bid.ts
  src/constants/schema.ts
  src/constants/sortType.ts
  src/hooks/useEditableNumberInput.ts
  src/pages/Bid.tsx
  src/pages/BidderList.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#85 fix: 타입 정리
  src/@types/Auction.d.ts
  src/@types/AuctionDetails.d.ts
  src/@types/AuctionItem.d.ts
  src/@types/Register.d.ts
  src/@types/myAuctionData.d.ts
  src/@types/productList.d.ts
  src/components/bid/Bid.test.tsx
  src/components/bid/EditBid.test.tsx
  src/components/details/AuctionItem.tsx
  src/components/details/queries.ts
  src/components/heart/queries.ts
  src/components/home/HomeAuctionItem.tsx
  src/components/home/queries.ts
  src/components/order/OrderHistoryProduct.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/PreEnrollProduct.tsx
  src/components/user/OngoingMyRegister.tsx
  src/components/user/PreEnrollMyRegister.tsx
  src/components/userAuction/queries.ts
  src/constants/queryKeys.ts
  src/hooks/useHistory.ts
  src/mocks/data/auctionDetailsData.ts
  src/mocks/data/homeAuctionsData.ts
  src/mocks/data/preRegisterHeartData.ts
  src/pages/AuctionDetails.tsx
  src/pages/Bid.tsx
  src/pages/BidderList.tsx
  src/pages/Heart.tsx
  src/pages/Home.tsx
  src/pages/PreAuction.tsx
  src/pages/ProductList.tsx
  src/pages/Register.tsx
  src/pages/UserParticipatedList.tsx
  src/pages/UserRegisteredList.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#87 Feat. 경매 페이지 유저/상태별 footer 구현 외
  src/components/details/BuyersFooter.tsx
  src/components/details/ConfirmationModal.tsx
  src/components/details/SellersFooter.tsx
  src/components/details/SuccessModal.tsx
  src/components/layout/Layout.tsx
  src/pages/AuctionDetails.tsx
  src/pages/PreAuction.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#89 Fix: 로그인 토큰 재정립
  src/api/axios.ts
  src/components/login/queries.ts
  src/hooks/useSignup.ts
  src/pages/Signup.tsx
Labels: ✨feature

#97 fix: sse refresh token 만료시 발생하는 error handling
  src/hooks/useSSE.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#94 feat: 프론트 데이터 및 타입 변경 , 입찰 및 입찰자 리스트 수정, 경매 상세정보 수정
  src/@types/AuctionDetails.d.ts
  src/@types/AuctionItem.d.ts
  src/@types/AuctionList.d.ts
  src/@types/Notification.d.ts
  src/@types/bid.d.ts
  src/@types/myAuctionData.d.ts
  src/@types/productList.d.ts
  src/components/bid/Bid.test.tsx
  src/components/bid/EditBid.test.tsx
  src/components/bid/queries.ts
  src/components/bidderList/queries.ts
  src/components/common/item/ProductItem.tsx
  src/components/details/BuyersFooter.tsx
  src/components/details/queries.ts
  src/components/heart/Heart.test.tsx
  src/components/heart/queries.ts
  src/components/home/Home.test.tsx
  src/components/home/HomeAuctionItem.tsx
  src/components/home/queries.ts
  src/components/notification/NotificationItem.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/queries.ts
  src/components/user/OngoingMyRegister.tsx
  src/components/user/queries.ts
  src/components/userAuction/queries.ts
  src/constants/queryKeys.ts
  src/hooks/useSSE.ts
  src/mocks/data/auctionDetailsData.ts
  src/mocks/data/bidderListData.ts
  src/mocks/data/homeAuctionsData.ts
  src/mocks/data/notificationData.ts
  src/mocks/data/preAuctionHeartData.ts
  src/mocks/handlers/notification.ts
  src/mocks/handlers/preRegisterHeart.ts
  src/pages/AuctionDetails.tsx
  src/pages/Bid.tsx
  src/pages/BidderList.tsx
  src/pages/Heart.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
  src/pages/PreAuctionDetails.tsx
  src/pages/ProductList.tsx
  src/pages/UserParticipatedList.tsx
  src/pages/UserRegisteredList.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#98 Feature: 홈페이지, 경매 등록 이미지 캐러셀 적용
  package-lock.json
  package.json
  src/components/common/CustomCarousel.tsx
  src/components/home/HomeAuctionItem.tsx
  src/components/home/HomeItemList.tsx
  src/components/register/ImageUploader.tsx
  src/components/register/RegisterCaution.tsx
  src/components/register/quries.ts
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/constants/caution.ts
  src/pages/Home.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#99 feat: Carousel 추가 및 적용, 경매 등록 수정
  package-lock.json
  package.json
  src/components/common/CustomCarousel.tsx
  src/components/home/HomeAuctionItem.tsx
  src/components/home/HomeItemList.tsx
  src/components/register/ImageUploader.tsx
  src/components/register/RegisterCaution.tsx
  src/components/register/quries.ts
  src/components/ui/button.tsx
  src/components/ui/carousel.tsx
  src/constants/caution.ts
  src/pages/Home.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#102 Feat: 사전경매 페이지 footer 구현
  src/components/details/BuyersFooter.tsx
  src/components/details/SellersFooter.tsx
  src/pages/AuctionDetails.tsx
  src/pages/PreAuctionDetails.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#103 feat: 사전 등록 수정 기능
  src/@types/AuctionDetails.d.ts
  src/@types/Register.d.ts
  src/components/details/queries.ts
  src/components/home/HomeAuctionItem.tsx
  src/components/register/quries.ts
  src/constants/route.ts
  src/pages/PreAuctionDetails.tsx
  src/pages/Register.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#104 dev to main
  src/@types/AuctionDetails.d.ts
  src/@types/Register.d.ts
  src/components/bid/Bid.test.tsx
  src/components/bid/EditBid.test.tsx
  src/components/details/BuyersFooter.tsx
  src/components/details/SellersFooter.tsx
  src/components/details/queries.ts
  src/components/home/CategoryList.tsx
  src/components/home/HomeAuctionItem.tsx
  src/components/register/quries.ts
  src/constants/categories.ts
  src/constants/route.ts
  src/mocks/data/auctionDetailsData.ts
  src/pages/AuctionDetails.tsx
  src/pages/PreAuctionDetails.tsx
  src/pages/Register.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#105 feat: 내가 등록한 경매 URL 수정
  src/components/common/item/ProductItem.tsx
  src/components/login/queries.ts
  src/components/order/OrderListTab.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/user/UserOrder.tsx
  src/components/user/UserProfile.tsx
  src/components/user/queries.ts
  src/hooks/useMyAuctionList.ts
  src/hooks/useProfile.ts
  src/pages/User.tsx
Labels: ✨feature

#112 fix: 사전 경매 수정시 카테고리 값 불러오기
  src/pages/Register.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#114 Bug: SSE 401 에러
  src/hooks/useSSE.ts
Labels: 🐛bug, 👩🏻‍💻frontend

#120 Feat / 좋아요한 사전경매 삭제
  src/components/heart/queries.ts
  src/constants/queryKeys.ts
  src/main.tsx
  src/mocks/data/notificationData.ts
  src/pages/Heart.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#122 fix: 시작가부터 입찰 가능
  src/constants/schema.ts
  src/hooks/useEditableNumberInput.ts
  src/pages/Bid.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#126 Feat: register post 및 patch loading
  src/components/common/atomic/TimeLabel.tsx
  src/components/register/ImageUploader.tsx
  src/components/register/quries.ts
  src/pages/Register.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#125 Feat: empty boundary 적용 및 기타 작업
  src/components/common/EmptyFallback.tsx
  src/components/home/CategoryList.tsx
  src/components/home/HomeItem.tsx
  src/components/home/HomeItemList.tsx
  src/components/home/queries.ts
  src/components/productList/queries.ts
  src/components/register/ImageUploader.tsx
  src/components/user/queries.ts
  src/components/userAuction/queries.ts
  src/constants/api.ts
  src/constants/emptyMessage.ts
  src/constants/queryKeys.ts
  src/hooks/useMyAuctionList.ts
  src/hooks/useProductList.ts
  src/mocks/handlers/ProductList.ts
  src/pages/Heart.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
  src/pages/ProductList.tsx
  src/pages/UserParticipatedList.tsx
  src/pages/UserRegisteredList.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#129 Feat: bidder list sort 및 접근 제한
  src/components/bidderList/queries.ts
  src/pages/BidderList.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#128 fix: footer notification query를 login 상황에서만 실행
  src/components/navigation/Navigation.tsx
  src/components/notification/queries.ts
Labels: 🐛bug, 👩🏻‍💻frontend

#132 Fix: 사전등록 수정시 이미지 처리 버그
  src/@types/AuctionDetails.d.ts
  src/@types/Register.d.ts
  src/components/register/ImageUploader.tsx
  src/hooks/useImageUploader.ts
  src/pages/PreAuctionDetails.tsx
  src/pages/Register.tsx
  src/utils/dataURLToFile.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#123 Feat: ProductItem 시간, style, Type 변경, 프로필 이미지 추가
  src/@types/AuctionItem.d.ts
  src/assets/icons/profile.svg
  src/assets/icons/profile_edit.svg
  src/components/common/Button.tsx
  src/components/common/ProductItem.tsx
  src/components/common/item/ProductItem.tsx
  src/components/login/queries.ts
  src/components/order/OrderHistoryProduct.tsx
  src/components/order/OrderListTab.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/PreEnrollProduct.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/components/profile/queries.ts
  src/components/user/OngoingMyRegister.tsx
  src/components/user/PreEnrollMyRegister.tsx
  src/components/user/UserOrder.tsx
  src/components/user/UserOrderList.tsx
  src/components/user/UserProfile.tsx
  src/constants/api.ts
  src/constants/queryKeys.ts
  src/constants/route.ts
  src/hooks/useProfile.ts
  src/hooks/useProfileImageUploader.ts
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  src/pages/User.tsx
Labels: ✨feature

#131 Feat: 경매 상세/사전 경매 상세 페이지 구현 완료
  package-lock.json
  package.json
  src/components/details/BuyersFooter.tsx
  src/components/details/SellersFooter.tsx
  src/components/details/queries.ts
  src/components/layout/Layout.tsx
  src/components/payment/PaymentForm.tsx
  src/constants/route.ts
  src/pages/AuctionDetails.tsx
  src/pages/Payment.tsx
  src/pages/PreAuctionDetails.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#139 Feat: 케로셀 구현 외
  src/components/details/ImageItem.tsx
  src/components/details/ImageList.tsx
  src/components/details/queries.ts
  src/hooks/useImageUrls.ts
  src/pages/AuctionDetails.tsx
  src/pages/PreAuctionDetails.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#141 Fix: rendering error
  src/api/axios.ts
  src/components/common/CustomCarousel.tsx
  src/components/common/boundary/APIAsyncBoundary.tsx
  src/components/common/boundary/LocalAPIAsyncBoundary.tsx
  src/components/common/loading/LocalSpinner.tsx
  src/components/details/queries.ts
  src/components/home/CategoryList.tsx
  src/components/login/queries.ts
  src/components/navigation/Navigation.tsx
  src/components/notification/queries.ts
  src/pages/Notification.tsx
  src/pages/PreAuctionDetails.tsx
  src/pages/Test.tsx
  src/router.tsx
  tsconfig.app.json
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#144 Feat: 결제 기능 추가 및 테스트 보완사항 수정
  public/mockServiceWorker.js
  src/@types/AuctionItem.d.ts
  src/components/address/queries.ts
  src/components/common/MenuAccordion.tsx
  src/components/common/ProductItem.tsx
  src/components/common/item/ProductItem.tsx
  src/components/order/OrderHistoryProduct.tsx
  src/components/order/OrderListTab.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/payment/PaymentForm.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/PreEnrollProduct.tsx
  src/components/productList/ProductButtons.tsx
  src/components/productList/ProductListTabs.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/components/profile/SelectBank.tsx
  src/components/user/OngoingMyRegister.tsx
  src/components/user/PreEnrollMyRegister.tsx
  src/components/user/UserOrderList.tsx
  src/components/user/UserOrderTab.tsx
  src/components/user/UserProfile.tsx
  src/constants/api.ts
  src/constants/bank.ts
  src/constants/queryKeys.ts
  src/constants/route.ts
  src/hooks/usePayment.ts
  src/hooks/useProfileImageUploader.ts
  src/hooks/useSignup.ts
  src/pages/AddressBook.tsx
  src/pages/Payment.tsx
  src/pages/PaymentSuccess.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  src/router.tsx
Labels: ✨feature

#143 Fix: 전체 기능 테스트 보완
  src/@types/AuctionDetails.d.ts
  src/assets/icons/in_box_edit_time.svg
  src/assets/icons/in_box_like.svg
  src/assets/icons/like_heart.svg
  src/assets/icons/modal_cancel.svg
  src/assets/icons/modal_edit.svg
  src/assets/icons/modal_share.svg
  src/assets/icons/my_participation_amount.svg
  src/components/bid/Bid.test.tsx
  src/components/bid/BidFooter.tsx
  src/components/bid/BidMain.tsx
  src/components/bid/EditBid.test.tsx
  src/components/bid/queries.ts
  src/components/bidderList/BidderListMain.tsx
  src/components/common/Button.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/CustomCarousel.tsx
  src/components/common/atomic/LikeCount.tsx
  src/components/common/atomic/MinPrice.tsx
  src/components/common/atomic/ParticipantCount.tsx
  src/components/common/atomic/TimeLabel.tsx
  src/components/common/item/AuctionItem.tsx
  src/components/common/route/PrivateRoute.tsx
  src/components/common/route/PublicRoute.tsx
  src/components/details/AuctionDetailsFooter.tsx
  src/components/details/BuyersFooter.tsx
  src/components/details/ConfirmationModal.tsx
  src/components/details/DetailsBasic.tsx
  src/components/details/ImageItem.tsx
  src/components/details/ImageList.tsx
  src/components/details/PreAuctionDetailsFooter.tsx
  src/components/details/ProgressBar.tsx
  src/components/details/SellersFooter.tsx
  src/components/details/SuccessModal.tsx
  src/components/details/queries.ts
  src/components/heart/queries.ts
  src/components/layout/GlobalLayout.tsx
  src/components/login/queries.ts
  src/components/notification/NotificationItem.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/components/register/ImageUploader.tsx
  src/hooks/useImageUploader.ts
  src/hooks/useImageUrls.ts
  src/hooks/useProfileImageUploader.ts
  src/mocks/data/auctionDetailsData.ts
  src/pages/AuctionDetails.tsx
  src/pages/Heart.tsx
  src/pages/Notification.tsx
  src/pages/PreAuctionDetails.tsx
  src/pages/Register.tsx
  src/provider/queryProvider.tsx
  src/utils/dataURLToFile.ts
Labels: ✨feature, 👩🏻‍💻frontend

#146 Feat: 주소 목록페이지 생성
  src/@types/Address.d.ts
  src/@types/AuctionItem.d.ts
  src/@types/AuctionList.d.ts
  src/components/address/FIndAddressButton.tsx
  src/components/common/atomic/CreatedAt.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/profile/FindAddressButton.tsx
  src/components/user/EndMyRegister.tsx
  src/components/user/OngoingMyRegister.tsx
  src/components/user/UserOrder.tsx
  src/components/user/UserOrderTab.tsx
  src/components/user/queries.ts
  src/components/userAuction/queries.ts
  src/constants/api.ts
  src/constants/route.ts
  src/constants/schema.ts
  src/hooks/useMyAuctionList.ts
  src/hooks/useProfileImageUploader.ts
  src/mocks/handlers/ProductList.ts
  src/pages/AuctionPayment.tsx
  src/pages/DeliveryAddressAdd.tsx
  src/pages/DeliveryAddressList.tsx
  src/pages/ProfileEdit.tsx
  src/pages/UserRegisteredList.tsx
  src/router.tsx
  src/utils/formatPhoneNumber.ts
Labels: ✨feature, 👩🏻‍💻frontend

#148 Feat: 기능 보완
  src/assets/icons/404_sign.svg
  src/assets/icons/default_image.svg
  src/assets/icons/empty.svg
  src/components/common/Button.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/boundary/EmptyBoundary.tsx
  src/components/common/boundary/RouteErrorBoundary.tsx
  src/components/details/AuctionDetailsFooter.tsx
  src/components/details/DetailsBasic.tsx
  src/components/details/PreAuctionDetailsFooter.tsx
  src/components/details/queries.ts
  src/components/home/CategoryList.tsx
  src/components/layout/Layout.tsx
  src/components/notification/NotificationItem.tsx
  src/components/register/quries.ts
  src/constants/categories.ts
  src/constants/notification.ts
  src/pages/PreAuctionDetails.tsx
  src/pages/Register.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#156 style: 버튼 및 카테고리 스타일 변경
  src/components/common/Button.tsx
  src/components/common/loading/ButtonSpinner.tsx
  src/components/home/CategoryList.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#160 Fix: isOrdered ture, false 수정 및 notification에서 payment -> shipping으로 수정
  src/components/order/OrderWonProduct.tsx
  src/constants/notification.ts
Labels: 🐛bug

#161 Fix: 테스트 보완사항
  src/components/common/item/AuctionItem.tsx
  src/components/common/item/ProductItem.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/user/EndMyRegister.tsx
  src/components/user/PreEnrollMyRegister.tsx
  src/constants/address.ts
  src/pages/AuctionShipping.tsx
  src/pages/DeliveryAddressAdd.tsx
  src/pages/DeliveryAddressEdit.tsx
  src/pages/DeliveryAddressList.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#166 fix: 로그인 페이지 스타일 수정, 회원가입, 프로필 수정 페이지 스타일 수정 및 useHooks 분리
  src/@types/user.ts
  src/components/login/queries.ts
  src/components/profile/queries.ts
  src/components/user/UserOrder.tsx
  src/components/user/UserProfile.tsx
  src/constants/schema.ts
  src/hooks/useProfile.ts
  src/hooks/useSignup.ts
  src/pages/Login.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  src/pages/User.tsx
  tailwind.config.js
Labels: ✨feature, 👩🏻‍💻frontend

#174 Fix: 2차 회의 기능 보완
  src/components/bid/Bid.test.tsx
  src/components/bid/BidFooter.tsx
  src/components/bid/BidMain.tsx
  src/components/bid/EditBid.test.tsx
  src/components/bid/queries.ts
  src/components/common/Button.tsx
  src/components/common/Confirm.tsx
  src/components/common/Modal.tsx
  src/components/common/error/AccessDenied.tsx
  src/components/details/AuctionDetailsFooter.tsx
  src/components/details/DetailsOption.tsx
  src/components/details/PreAuctionDetailsFooter.tsx
  src/components/details/ProgressBar.tsx
  src/components/details/queries.ts
  src/components/layout/GlobalLayout.tsx
  src/components/layout/RealTimeNotification.tsx
  src/components/notification/NotificationItem.tsx
  src/components/profile/Modal.tsx
  src/components/profile/SelectBank.tsx
  src/components/profile/SelectCountry.tsx
  src/constants/confirmMessage.ts
  src/constants/emptyMessage.ts
  src/constants/schema.ts
  src/pages/AuctionDetails.tsx
  src/pages/AuctionShipping.tsx
  src/pages/PreAuctionDetails.tsx
  src/pages/Register.tsx
  tailwind.config.js
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#173 Fix: 2차 기능 테스트 수정사항 변경
  src/@types/AuctionItem.ts
  src/api/axios.ts
  src/assets/icons/blue_notice.svg
  src/assets/icons/btnG_naverIcon.png
  src/assets/icons/btnG_naver_icon.svg
  src/assets/icons/kakaotalk_sharing_btn_small.png
  src/assets/icons/kakaotalk_sharing_btn_small.svg
  src/assets/icons/successful_auction_win.svg
  src/components/address/queries.ts
  src/components/common/atomic/CreatedAt.tsx
  src/components/common/atomic/Price.tsx
  src/components/common/item/AuctionItem.tsx
  src/components/details/DetailsBasic.tsx
  src/components/heart/queries.ts
  src/components/home/CategoryList.tsx
  src/components/home/HomeItem.tsx
  src/components/order/OrderHistoryProduct.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/PreAuctionProduct.tsx
  src/components/profile/ProfileImageUploader.tsx
  src/components/user/EndMyRegister.tsx
  src/components/user/OngoingMyRegister.tsx
  src/components/user/PreAuctionMyRegister.tsx
  src/components/user/UserOrder.tsx
  src/components/user/UserProfile.tsx
  src/components/user/queries.ts
  src/constants/routes.ts
  src/hooks/useMyAuctionList.ts
  src/hooks/useSignup.ts
  src/mocks/data/preEnrollData.ts
  src/pages/AuctionShipping.tsx
  src/pages/DeliveryAddressAdd.tsx
  src/pages/DeliveryAddressEdit.tsx
  src/pages/DeliveryAddressList.tsx
  src/pages/EditAddress.tsx
  src/pages/Heart.tsx
  src/pages/Login.tsx
  src/pages/ProductList.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  src/pages/UserParticipatedList.tsx
  src/pages/UserPreRegisteredList.tsx
  src/pages/UserRegisteredList.tsx
  src/store/index.ts
  src/store/profileEditSlice.ts
  src/store/signupSlice.ts
  src/utils/formatPhoneNumber.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#181 Feat: 3차 회의 기능 보완
  src/components/bid/BidMain.tsx
  src/components/details/AuctionDetailsFooter.tsx
  src/components/details/PreAuctionDetailsFooter.tsx
  src/components/details/ProgressBar.tsx
  src/components/details/queries.ts
  src/components/heart/queries.ts
  src/components/notification/queries.ts
  src/components/productList/PreAuctionProduct.tsx
  src/components/productList/queries.ts
  src/components/user/UserProfile.tsx
  src/constants/schema.ts
  src/hooks/useEditableNumberInput.ts
  src/hooks/useEndAuction.ts
  src/pages/AuctionDetails.tsx
  src/pages/Heart.tsx
  src/pages/Register.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#184 Fix: 디자인 수정
  src/components/common/CustomCarousel.tsx
  src/components/details/DetailsBasic.tsx
  src/components/details/ProgressBar.tsx
  src/components/home/CategoryList.tsx
  src/components/home/HomeItem.tsx
  src/pages/AuctionDetails.tsx
  src/pages/PreAuctionDetails.tsx
Labels: ✨feature, 👩🏻‍💻frontend
