Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2024-11, with the labels that each got.

#186 Fix: 모바일 디자인 수정
  src/app/layout/ui/Layout.tsx
  src/app/main.tsx
  src/components/details/PreAuctionDetailsFooter.tsx
  src/components/details/queries.ts
  src/components/heart/Heart.test.tsx
  src/components/heart/queries.ts
  src/components/home/Home.test.tsx
  src/components/order/OrderListTab.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/PreAuctionProduct.tsx
  src/components/productList/queries.ts
  src/components/profile/ProfileImageUploader.tsx
  src/components/user/UserOrder.tsx
  src/components/user/UserOrderList.tsx
  src/components/user/UserOrderTab.tsx
  src/components/user/UserProfile.tsx
  src/constants/navIcons.ts
  src/constants/routeInfo.ts
  src/entities/product/ui/ProductItem.tsx
  src/mocks/data/notificationData.ts
  src/pages/heart/ui/Heart.tsx
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressAdd.tsx
  src/pages/payment/ui/PaymentAddressEdit.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/pages/sign-up/ui/Signup.tsx
  src/pages/user/ui/UserProfileEdit.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#189 Feat: 통합 테스트 코드 구현
  src/@types/Address.ts
  src/@types/AuctionItem.ts
  src/components/address/Address.test.tsx
  src/components/address/queries.ts
  src/components/login/Login.test.tsx
  src/components/productList/PreAuctionProduct.tsx
  src/features/sign-up/test/Signup.test.tsx
  src/hooks/usePayment.ts
  src/mocks/data/homeAuctionsData.ts
  src/mocks/data/preAuctionHeartData.ts
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressAdd.tsx
  src/pages/payment/ui/PaymentAddressEdit.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/pages/sign-up/ui/Signup.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#193 Fix: 디자인 수정
  src/app/layout/ui/Layout.tsx
  src/components/details/DetailsOption.tsx
  src/components/details/PreAuctionDetailsFooter.tsx
  src/components/home/HomeItem.tsx
  src/components/navigation/Navigation.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/user/EndMyRegister.tsx
  src/entities/auction/ui/AuctionItem.tsx
  src/features/notification/ui/NotificationItem.tsx
  src/features/notification/ui/RealTimeNotificationItem.tsx
  src/features/register/ui/ImageUploader.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/heart/ui/Heart.tsx
  src/pages/notification/ui/Notification.tsx
  src/shared/shadcn/ui/button.tsx
  src/shared/ui/AccessDenied.tsx
  src/shared/ui/Button.tsx
  src/shared/ui/Confirm.tsx
  src/shared/ui/CreatedAt.tsx
  src/shared/ui/LikeCount.tsx
  src/shared/ui/ParticipantCount.tsx
  src/shared/ui/Price.tsx
  src/shared/ui/boundary/APIAsyncBoundary.tsx
  src/shared/ui/boundary/GlobalAsyncBoundary.tsx
  src/shared/ui/boundary/LocalAPIAsyncBoundary.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#195 Fix: 750px 화면 스타일 수정
  src/components/address/queries.ts
  src/components/user/UserOrder.tsx
  src/components/user/UserProfile.tsx
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressAdd.tsx
  src/pages/payment/ui/PaymentAddressEdit.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/pages/sign-up/ui/Signup.tsx
  src/pages/user/ui/UserProfileEdit.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#197 refactor: empty boundary 개선 및 폴더 구조 개선
  src/components/details/DetailsBasic.tsx
  src/components/home/BestItemList.tsx
  src/components/home/HomeItem.tsx
  src/components/home/ImminentItemList.tsx
  src/components/home/PreAuctionItemList.tsx
  src/components/home/queries.ts
  src/components/user/queries.ts
  src/constants/routeInfo.ts
  src/features/heart/api/deletePreAuctionHeart.ts
  src/features/heart/api/getPreAuctionHeartList.ts
  src/features/heart/api/index.ts
  src/features/heart/index.ts
  src/features/heart/model/index.ts
  src/features/heart/model/useDeletePreAuctionHeart.ts
  src/features/heart/model/useGetPreAuctionHeartList.ts
  src/features/heart/test/Heart.test.tsx
  src/features/heart/ui/HeartList.tsx
  src/features/heart/ui/index.ts
  src/features/notification/model/useGetNotifications.ts
  src/features/register/ui/RegisterForm.tsx
  src/pages/heart/ui/Heart.tsx
  src/pages/home/api/getBestAuctions.ts
  src/pages/home/api/getImminentAuctions.ts
  src/pages/home/api/getPreAuctions.ts
  src/pages/home/api/index.ts
  src/pages/home/lib/index.ts
  src/pages/home/lib/useScrollDetection.ts
  src/pages/home/model/index.ts
  src/pages/home/model/useGetBestAuctions.ts
  src/pages/home/model/useGetImminentAuctions.ts
  src/pages/home/model/useGetPreAuctions.ts
  src/pages/home/test/Home.test.tsx
  src/pages/home/ui/BestItemList.tsx
  src/pages/home/ui/CategoryList.tsx
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeItemField.tsx
  src/pages/home/ui/HomeRegisterBtn.tsx
  src/pages/home/ui/ImminentItemList.tsx
  src/pages/home/ui/PreAuctionItemList.tsx
  src/pages/notification/ui/Notification.tsx
  src/pages/product-list/ui/ProductList.tsx
  src/pages/user/ui/UserParticipatedList.tsx
  src/pages/user/ui/UserPreRegisteredList.tsx
  src/pages/user/ui/UserRegisteredList.tsx
  src/shared/constants/categories.ts
  src/shared/constants/index.ts
  src/shared/index.ts
  src/shared/lib/EmptyError.ts
  src/shared/lib/index.ts
  src/shared/ui/EmptyFallback.tsx
  src/shared/ui/boundary/APIAsyncBoundary.tsx
  src/shared/ui/boundary/EmptyBoundary.tsx
  src/shared/ui/boundary/LocalAPIAsyncBoundary.tsx
  src/shared/ui/boundary/index.ts
  src/shared/ui/index.ts
Labels: ✨feature, 👩🏻‍💻frontend

#198 fix: address 테스트 코드 수정
  src/components/address/Address.test.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#204 Chore: 배포 workflow 작성
  .github/workflows/CD.yml
  src/app/main.tsx
  src/shared/test/mockServiceWorker.js
Labels: ✨feature, 🧹cleanup

#206 fix: 빌드 파일에 msw 파일 제거
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/app/main.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 🐛bug

#209 Refactor: 폴더 구조 정리
  .github/workflows/deploy.yml
  build.sh
  src/app/layout/config/index.ts
  src/app/layout/config/navIcons.ts
  src/app/layout/config/routeInfo.ts
  src/app/layout/index.ts
  src/app/layout/ui/LayoutWithNav.tsx
  src/app/layout/ui/Navigation.tsx
  src/app/layout/ui/index.ts
  src/app/router.tsx
  src/components/settlement/queries.ts
  src/entities/auction/model/types/base.ts
  src/entities/auction/model/types/details.ts
  src/entities/auction/model/types/index.ts
  src/entities/auction/model/types/item.ts
  src/entities/auction/model/types/list.ts
  src/entities/auction/model/types/userParticipated.ts
  src/entities/auction/model/types/userRegistered.ts
  src/entities/index.ts
  src/features/bid/config/index.ts
  src/features/bid/config/type.ts
  src/features/bid/ui/BidForm.tsx
  src/features/heart/test/Heart.test.tsx
  src/features/heart/ui/HeartList.tsx
  src/features/notification/test/Notification.test.tsx
  src/features/profile/model/index.ts
  src/mocks/data/auctionDetailsData.ts
  src/mocks/data/homeAuctionsData.ts
  src/mocks/data/notificationData.ts
  src/mocks/data/preAuctionHeartData.ts
  src/pages/home/test/Home.test.tsx
  src/pages/home/ui/BestItemList.tsx
  src/pages/home/ui/ImminentItemList.tsx
  src/pages/home/ui/PreAuctionItemList.tsx
  src/pages/settlement/api/getBidderList.ts
  src/pages/settlement/api/index.ts
  src/pages/settlement/config/constants.ts
  src/pages/settlement/config/index.ts
  src/pages/settlement/config/type.ts
  src/pages/settlement/model/index.ts
  src/pages/settlement/model/useGetBidderList.ts
  src/pages/settlement/ui/Settlement.tsx
  src/pages/settlement/ui/SettlementMain.tsx
  src/shared/assets/test/Nike_RedWhite_Thumbnail.jpeg
  src/shared/assets/test/adidas_superstar.jpeg
  src/shared/assets/test/jordan_black.jpeg
  src/shared/assets/test/jordan_blue.jpeg
  src/shared/assets/test/jordan_red.jpeg
  src/shared/assets/test/newbalance_993.jpeg
  src/shared/ui/AuctionItem.tsx
  src/shared/ui/index.ts
  vite.config.ts
Labels: ✨feature, 👩🏻‍💻frontend

#212 Refactoring: 폴더 구조 이동
  src/app/router.tsx
  src/entities/address/address.ts
  src/entities/address/index.ts
  src/entities/auction/model/types/index.ts
  src/entities/auction/model/types/myAuctionData.ts
  src/entities/auction/model/types/userParticipated.ts
  src/entities/user/index.ts
  src/entities/user/user.ts
  src/features/address/api/addAddress.ts
  src/features/address/api/editAddress.ts
  src/features/address/config/address.ts
  src/features/address/config/index.ts
  src/features/address/model/useEditAddress.ts
  src/features/address/model/usePostAddress.ts
  src/features/address/model/usePostPayment.ts
  src/features/auth/api/postSignup.ts
  src/features/auth/model/usePostSignup.ts
  src/features/profile/model/useProfile.ts
  src/features/user/api/getAuctionEndRegister.ts
  src/features/user/api/getAuctionOngoingRegister.ts
  src/features/user/api/getAuctionPreAuctionRegister.ts
  src/features/user/api/getMyHistoryAuction.ts
  src/features/user/api/getMyLostAuction.ts
  src/features/user/api/getMyWonAuction.ts
  src/features/user/ui/UserOrder.tsx
  src/features/user/ui/UserProfile.tsx
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressAdd.tsx
  src/pages/payment/ui/PaymentAddressEdit.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/pages/product-list/ui/ProductList.tsx
  src/pages/sign-up/ui/Signup.tsx
  src/pages/user/ui/UserParticipatedList.tsx
  src/pages/user/ui/UserPreRegisteredList.tsx
  src/pages/user/ui/UserProfileEdit.tsx
  src/pages/user/ui/UserRegisteredList.tsx
Labels: 🧹cleanup

#211 Fix: 기능 개선
  src/app/layout/ui/GlobalLayout.tsx
  src/app/layout/ui/Layout.tsx
  src/app/main.tsx
  src/features/details/model/useToggleAuctionDetailsHeart.ts
  src/features/heart/model/useDeletePreAuctionHeart.ts
  src/features/product-list/model/useToggleAuctionListHeart.ts
  src/shared/ui/AuctionItem.tsx
  src/shared/ui/Modal.tsx
  tailwind.config.js
Labels: ✨feature, 👩🏻‍💻frontend

#217 Feat: setupMocks 함수 분리 및 로컬 백엔드와 분리
  src/app/main.tsx
  src/shared/test/setupMocks.ts
Labels: ⚙️chore, 🧹cleanup

#216 style: modal 수정
  src/shared/ui/Confirm.tsx
  src/shared/ui/Modal.tsx
Labels: ✨feature

#218 Refactor: Empty Boundary 개선
  src/features/heart/api/getPreAuctionHeartList.ts
  src/features/heart/ui/HeartList.tsx
  src/features/notification/api/getNotification.ts
  src/features/notification/model/useDeleteNotification.ts
  src/features/notification/model/useGetNotifications.ts
  src/features/notification/model/useReadNotification.ts
  src/features/notification/ui/NotificationItem.tsx
  src/features/notification/ui/NotificationList.tsx
  src/features/notification/ui/index.ts
  src/features/product-list/index.ts
  src/features/product-list/model/useToggleAuctionListHeart.ts
  src/pages/heart/ui/Heart.tsx
  src/pages/home/api/getBestAuctions.ts
  src/pages/home/api/getImminentAuctions.ts
  src/pages/home/api/getPreAuctions.ts
  src/pages/home/ui/BestItemList.tsx
  src/pages/home/ui/CategoryList.tsx
  src/pages/home/ui/ImminentItemList.tsx
  src/pages/home/ui/PreAuctionItemList.tsx
  src/pages/notification/ui/Notification.tsx
  src/pages/product-list/ui/ProductList.tsx
  src/pages/user/ui/UserParticipatedList.tsx
  src/pages/user/ui/UserPreRegisteredList.tsx
  src/pages/user/ui/UserRegisteredList.tsx
  src/shared/index.ts
  src/shared/lib/EmptyError.ts
  src/shared/lib/index.ts
  src/shared/ui/EmptyFallback.tsx
  src/shared/ui/boundary/APIAsyncBoundary.tsx
  src/shared/ui/boundary/EmptyBoundary.tsx
  src/shared/ui/boundary/LocalAPIAsyncBoundary.tsx
  src/shared/ui/boundary/index.ts
  src/shared/ui/index.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#220 fix: 경매 수정 새로고침 시 훅 에러 해결
  src/app/router.tsx
  src/features/details/index.ts
  src/features/details/model/index.ts
  src/features/details/model/useGetPreAuctionDetails.ts
  src/features/details/model/useGetPreAuctionDetailsWithSuspense.ts
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/features/edit-auction/api/index.ts
  src/features/edit-auction/api/patchPreAuction.ts
  src/features/edit-auction/index.ts
  src/features/edit-auction/model/index.ts
  src/features/edit-auction/model/usePatchPreAuction.ts
  src/features/register/api/index.ts
  src/features/register/api/postAuction.ts
  src/features/register/index.ts
  src/features/register/model/index.ts
  src/features/register/model/usePostAuction.ts
  src/features/register/ui/ImageUploader.tsx
  src/features/register/ui/RegisterCaution.tsx
  src/features/register/ui/index.ts
  src/pages/edit-auction/index.ts
  src/pages/edit-auction/ui/EditAuction.tsx
  src/pages/edit-auction/ui/index.ts
  src/pages/index.ts
  src/pages/register/index.ts
  src/pages/register/ui/Register.tsx
  src/pages/register/ui/index.ts
  src/shared/shadcn/index.ts
  src/shared/shadcn/ui/index.ts
  src/shared/shadcn/ui/skeleton.tsx
  src/shared/ui/AuctionForm.tsx
  src/shared/ui/index.ts
Labels: ✨feature, 👩🏻‍💻frontend

#222 Fix : form defaultValues 설정
  src/shared/ui/AuctionForm.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#224 Fix: 배포 workflow 수정
  .github/workflows/deploy.yml
  src/app/main.tsx
  src/shared/test/setupMocks.ts
Labels: ⚙️chore, ✨feature, 🐛bug, 👩🏻‍💻frontend

#226 fix: .env.production 추가
  .github/workflows/deploy.yml
Labels: ✨feature, 👩🏻‍💻frontend

#228 Refactor: 서버 API 변경 사항 작업
  .github/workflows/deploy.yml
  src/entities/auction/model/types/base.ts
  src/entities/auction/model/types/details.ts
  src/entities/auction/model/types/item.ts
  src/entities/auction/model/types/userParticipated.ts
  src/entities/auction/model/types/userRegistered.ts
  src/entities/index.ts
  src/features/bid/test/Bid.test.tsx
  src/features/bid/test/EditBid.test.tsx
  src/features/details/api/convertAuction.ts
  src/features/details/api/deletePreAuction.ts
  src/features/details/api/getPreAuctionDetails.ts
  src/features/details/api/heartAuction.ts
  src/features/details/model/useConvertAuction.ts
  src/features/details/model/useGetPreAuctionDetails.ts
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsFooter.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/features/edit-auction/api/patchPreAuction.ts
  src/features/edit-auction/model/usePatchPreAuction.ts
  src/features/heart/api/deletePreAuctionHeart.ts
  src/features/heart/api/getPreAuctionHeartList.ts
  src/features/heart/api/index.ts
  src/features/heart/model/useDeletePreAuctionHeart.ts
  src/features/heart/model/useGetPreAuctionHeartList.ts
  src/features/heart/ui/HeartList.tsx
  src/features/product-list/ui/PreAuctionProduct.tsx
  src/features/register/ui/ImageUploader.tsx
  src/features/user/ui/PreAuctionMyRegister.tsx
  src/mocks/data/auctionDetailsData.ts
  src/mocks/data/homeAuctionsData.ts
  src/mocks/data/preAuctionHeartData.ts
  src/mocks/handlers/auctionDetailPage.ts
  src/mocks/handlers/myAuctuon.ts
  src/mocks/handlers/preRegisterHeart.ts
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/home/api/getBestAuctions.ts
  src/pages/home/api/getImminentAuctions.ts
  src/pages/home/api/getPreAuctions.ts
  src/pages/home/model/useGetBestAuctions.ts
  src/pages/home/model/useGetImminentAuctions.ts
  src/pages/home/model/useGetPreAuctions.ts
  src/pages/home/ui/PreAuctionItemList.tsx
  src/pages/product-list/ui/ProductList.tsx
  src/pages/settlement/api/getBidderList.ts
  src/pages/settlement/model/useGetBidderList.ts
  src/pages/settlement/ui/SettlementMain.tsx
  src/pages/user/ui/UserPreRegisteredList.tsx
  src/shared/constants/apiEndPoint.ts
  src/shared/constants/queryKeys.ts
  src/shared/ui/AccessDenied.tsx
  src/shared/ui/AuctionForm.tsx
  src/shared/ui/boundary/APIAsyncBoundary.tsx
  src/shared/ui/index.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#227 Feat: storybook 테스트 초기 셋팅 및 예제 코드 추가
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/entities/auction/model/types/userParticipated.ts
  src/features/address/test/Address.test.tsx
  src/features/product-list/ui/OngoingProduct.tsx
  src/features/product-list/ui/PreAuctionProduct.tsx
  src/features/register/test/Register.test.tsx
  src/features/user/ui/EndMyRegister.tsx
  src/features/user/ui/OngoingMyRegister.tsx
  src/features/user/ui/OrderHistoryProduct.tsx
  src/features/user/ui/OrderLostProduct.tsx
  src/features/user/ui/PreAuctionMyRegister.tsx
  src/pages/payment/ui/PaymentSuccess.tsx
  src/shared/test/setupTests.ts
  src/shared/ui/ProductItem.tsx
  src/shared/ui/index.ts
  src/shared/ui/product/story/ProductItem.stories.tsx
  src/shared/ui/product/test/ProductItem.test.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tsconfig.base.json
  vite.config.ts
Labels: ✨feature, 👩🏻‍💻frontend

#229 Refactoring: 수정된 auction api에 맞춰 코드 수정
  src/entities/auction/model/types/userParticipated.ts
  src/features/address/api/getAddressDetail.ts
  src/features/address/model/usePostPayment.ts
  src/features/product-list/api/getEnrollProductList.ts
  src/features/user/api/getMyLostAuction.ts
  src/features/user/api/getMyWonAuction.ts
  src/pages/payment/ui/Payment.tsx
  src/pages/user/ui/UserParticipatedList.tsx
  src/shared/constants/apiEndPoint.ts
Labels: 🧹cleanup

#230 Feat: 회원 탈퇴 기능추가
  src/features/product-list/model/useProductList.ts
  src/features/user/api/deleteUsers.ts
  src/features/user/model/useDeleteUsers.ts
  src/features/user/model/useHistory.ts
  src/features/user/model/useMyAuctionList.ts
  src/features/user/ui/UserOrderList.tsx
  src/pages/product-list/ui/ProductList.tsx
  src/pages/user/ui/UserParticipatedList.tsx
  src/pages/user/ui/UserPreRegisteredList.tsx
  src/pages/user/ui/UserRegisteredList.tsx
  src/shared/constants/confirmMessage.ts
Labels: ✨feature
