Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2024-09, with the labels that each got.

#37 Feat: 배달 정보 입력 페이지 생성 및 로그인 구현
  .env
  .eslintrc.cjs
  src/@types/kakao.d.ts
  src/@types/user.d.ts
  src/App.tsx
  src/api/axios.ts
  src/assets/images/naver_login.png
  src/components/login/queries.ts
  src/components/profile/SelectBank.tsx
  src/components/ui/input.tsx
  src/constants/api.ts
  src/constants/route.ts
  src/constants/schema.ts
  src/hooks/useAuth.ts
  src/hooks/useKakaoInit.ts
  src/hooks/useSignup.ts
  src/main.tsx
  src/mocks/broswer.ts
  src/mocks/handlers/Login.ts
  src/pages/AddressBook.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  src/pages/Test.tsx
  src/provider/loginProvider.tsx
  src/routing.tsx
  src/store/authSlice.ts
  src/store/index.ts
  src/utils/tokenUtils.ts
  tsconfig.base.json
  vite.config.ts
Labels: ✨feature

#41 feat & test: 좋아요 페이지 기능 구현 및 테스트 작성
  src/@types/Product.d.ts
  src/components/bid/Bid.test.tsx
  src/components/common/AuctionItem.tsx
  src/components/heart/Heart.test.tsx
  src/components/heart/queries.ts
  src/components/notification/Notification.test.tsx
  src/constants/api.ts
  src/constants/queryKeys.ts
  src/constants/route.ts
  src/mocks/broswer.ts
  src/mocks/data/preRegisterHeartData.ts
  src/mocks/handlers/preRegisterHeart.ts
  src/pages/Heart.tsx
  src/routing.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#42 fix: 실시간 알림 및 알림함 데이터 타입 및 기능 수정
  src/@types/Notification.d.ts
  src/components/layout/GlobalLayout.tsx
  src/components/layout/RealTimeNotification.test.tsx
  src/components/layout/RealTimeNotification.tsx
  src/components/notification/Notification.test.tsx
  src/components/notification/NotificationItem.tsx
  src/constants/notification.ts
  src/mocks/data/notificationData.ts
  src/mocks/data/realTimeNotificationData.ts
  src/mocks/handlers/realTimeNotification.ts
Labels: ✨feature, 👩🏻‍💻frontend

#46 Feat: Suspense 적용 및 변수명 auction으로 통일
  .eslintrc.cjs
  src/@types/Auction.d.ts
  src/@types/Product.d.ts
  src/@types/myAuctionData.d.ts
  src/components/bid/Bid.test.tsx
  src/components/bid/EditBid.test.tsx
  src/components/bidderList/queries.ts
  src/components/common/AuctionItem.tsx
  src/components/common/Button.tsx
  src/components/common/atomic/LikeCount.tsx
  src/components/common/atomic/MinPrice.tsx
  src/components/common/atomic/ParticipantCount.tsx
  src/components/common/atomic/TimeLabel.tsx
  src/components/common/form/FormField.tsx
  src/components/common/loading/LoadingSpinner.tsx
  src/components/details/queries.ts
  src/components/heart/Heart.test.tsx
  src/components/heart/queries.ts
  src/components/home/Home.test.tsx
  src/components/home/HomeAuctionItem.tsx
  src/components/home/HomeItemList.tsx
  src/components/home/HomeProductItem.tsx
  src/components/home/HomeRegisterBtn.tsx
  src/components/home/queries.ts
  src/components/layout/Layout.tsx
  src/components/navigation/Navigation.tsx
  src/components/notification/Notification.test.tsx
  src/components/notification/queries.ts
  src/constants/navIcons.ts
  src/constants/queryKeys.ts
  src/index.css
  src/mocks/broswer.ts
  src/mocks/data/auctionDetailsData.ts
  src/mocks/data/homeAuctionsData.ts
  src/mocks/data/homeProductsData.ts
  src/mocks/data/preRegisterHeartData.ts
  src/mocks/handlers/auctionDetails.ts
  src/mocks/handlers/home.ts
  src/mocks/handlers/notification.ts
  src/mocks/handlers/preRegisterHeart.ts
  src/mocks/handlers/productDetails.ts
  src/pages/AddressBook.tsx
  src/pages/Bid.tsx
  src/pages/BidderList.tsx
  src/pages/Heart.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Register.tsx
  src/pages/Signup.tsx
  src/routing.tsx
  src/utils/truncateText.ts
Labels: ✨feature, 👩🏻‍💻frontend

#48 Fix: User 페이지 스타일 변경
  src/api/axios.ts
  src/assets/icons/auction.svg
  src/assets/icons/failed_auction.svg
  src/assets/icons/ongoing_auction.svg
  src/assets/icons/pre_auction.svg
  src/assets/icons/successful_auction.svg
  src/components/login/queries.ts
  src/components/user/UserOrder.tsx
  src/components/user/UserOrderList.tsx
  src/constants/sortType.ts
  src/mocks/browser.ts
  src/pages/OrderHistory.tsx
  src/pages/Signup.tsx
  src/pages/User.tsx
  src/pages/UserRegisteredList.tsx
  src/utils/tokenUtils.ts
Labels: ✨feature, 👩🏻‍💻frontend

#59 Fix: 로그인 버튼 스타일 수정
  src/hooks/useSignup.ts
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/pages/User.tsx
Labels: 👩🏻‍💻frontend

#67 Feat: 인가되지 않은 사용자에 대한 서비스 제한 기능
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/common/Button.tsx
  src/components/common/ButtonSpinner.tsx
  src/components/common/ErrorFallback.tsx
  src/components/common/NoData.tsx
  src/components/common/NotFound.tsx
  src/components/common/form/FormField.tsx
  src/components/common/item/AuctionItem.tsx
  src/components/common/item/ProductItem.tsx
  src/components/common/loadingAndError/AsyncBoundary.tsx
  src/components/common/loadingAndError/ButtonSpinner.tsx
  src/components/common/loadingAndError/ErrorFallback.tsx
  src/components/common/loadingAndError/ErrorMessage.tsx
  src/components/common/loadingAndError/GlobalSpinner.tsx
  src/components/common/loadingAndError/NoData.tsx
  src/components/common/loadingAndError/NotFound.tsx
  src/components/common/route/PrivateRoute.tsx
  src/components/common/route/PublicRoute.tsx
  src/components/heart/queries.ts
  src/components/order/OrderHistoryProduct.tsx
  src/components/order/OrderLostProduct.tsx
  src/components/order/OrderWonProduct.tsx
  src/components/productList/OngoingProduct.tsx
  src/components/productList/PreEnrollProduct.tsx
  src/components/register/RegisterLabel.tsx
  src/components/user/OngoingMyRegister.tsx
  src/components/user/PreEnrollMyRegister.tsx
  src/constants/api.ts
  src/mocks/handlers/preRegisterHeart.ts
  src/pages/Bid.tsx
  src/pages/BidderList.tsx
  src/pages/Heart.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
  src/pages/Register.tsx
  src/pages/User.tsx
  src/provider/loginProvider.tsx
  src/router.tsx
Labels: ✨feature, 👩🏻‍💻frontend
