Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2024-08, with the labels that each got.

#13 Feat: 상품 목록 페이지 컴포넌트로 분리, 공통 Layout에 Header 수정
  .eslintrc.cjs
  src/App.tsx
  src/assets/fonts/Pretendard-Black.woff
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-ExtraBold.woff
  src/assets/fonts/Pretendard-ExtraLight.woff
  src/assets/fonts/Pretendard-Light.woff
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-Thin.woff
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/common/Button.tsx
  src/components/common/Popup.tsx
  src/components/common/PopupBody.tsx
  src/components/common/PopupTitle.tsx
  src/components/product/OngoingProduct.tsx
  src/components/product/ProductButtons.tsx
  src/components/product/ProductListTabs.tsx
  src/components/product/UpcomingProduct.tsx
  src/components/profile/Modal.tsx
  src/components/profile/ProfileInput.tsx
  src/components/profile/SelectCountry.tsx
  src/constants/route.ts
  src/main.tsx
  src/mocks/data/ongoingData.ts
  src/pages/MainPage.tsx
  src/pages/ProductList.tsx
  src/pages/ProductListPage.tsx
  src/pages/ProfileEditPage.tsx
  src/pages/home.tsx
  src/provider/queryProvider.tsx
  src/routing.tsx
  src/ui/Footer.tsx
  src/ui/Header.tsx
  src/ui/Layout.tsx
Labels: ✨feature

#23 Feat: 테스트 코드 작성, MSW Api 연결, 상품 목록 페이지 무한스크롤 구현
  .eslintrc.cjs
  package-lock.json
  package.json
  public/bank_CITY.svg
  public/bank_IBK.svg
  public/bank_KB.svg
  public/bank_Kbank.svg
  public/bank_NH.svg
  public/bank_hana.svg
  public/bank_kakao.svg
  public/bank_saemaul.svg
  public/bank_shinhan.svg
  public/bank_uri.svg
  public/kakao_login_medium_narrow.png
  public/modal_X_button.svg
  public/더보기.svg
  src/api/login.api.ts
  src/api/product.api.ts
  src/components/common/Button.tsx
  src/components/common/Popup.tsx
  src/components/common/PopupTitle.tsx
  src/components/common/ProductLists.tsx
  src/components/common/XButton.tsx
  src/components/mypage/MyPageOrder.tsx
  src/components/mypage/MyPageProfile.tsx
  src/components/product/OngoingProduct.tsx
  src/components/product/ProductButtons.tsx
  src/components/product/UpcomingProduct.tsx
  src/components/profile/Modal.tsx
  src/components/profile/ProfileInput.tsx
  src/components/profile/SelectBank.tsx
  src/components/profile/SelectCountry.tsx
  src/components/tests/Mypage.spec.tsx
  src/components/tests/ProfileEdit.spec.tsx
  src/components/tests/Signup.spec.tsx
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/useFilterButtons.ts
  src/hooks/useProductList.ts
  src/mocks/broswer.ts
  src/mocks/data/ongoingData.ts
  src/mocks/data/upcomingData.ts
  src/mocks/handlers/ProductList.ts
  src/mocks/handlers/test.ts
  src/models/productList.ts
  src/pages/Login.tsx
  src/pages/ProductList.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  tsconfig.base.json
  vite.config.ts
Labels: ✨feature

#29 test & feat : 경매 등록 테스트 코드 작성 및 기능 구현
  .eslintrc.cjs
  package-lock.json
  package.json
  public/adidas_superstar.jpeg
  public/delete.svg
  public/jordan-black.jpeg
  public/jordan-blue.jpeg
  public/newbalance_993.jpeg
  public/notice.svg
  public/notice_red.svg
  src/@types/Product.d.ts
  src/components/Layout.tsx
  src/components/Navigation.tsx
  src/components/common/CautionCheck.tsx
  src/components/common/Check.tsx
  src/components/common/ErrorMessage.tsx
  src/components/form/FormField.tsx
  src/components/home/CategoryList.tsx
  src/components/home/HomeItem.tsx
  src/components/home/HomeItemList.tsx
  src/components/home/HomeProductItem.tsx
  src/components/home/HomeRegisterBtn.tsx
  src/components/home/queries.ts
  src/components/queryKeys.ts
  src/components/register/AddImageButton.tsx
  src/components/register/ImageUploader.tsx
  src/components/register/RegisterCaution.tsx
  src/components/register/RegisterLabel.tsx
  src/components/ui/select.tsx
  src/constants/api.ts
  src/constants/schema.ts
  src/hooks/useDragAndDrop.ts
  src/hooks/useEditableNumberInput.ts
  src/hooks/useImageUploader.ts
  src/index.css
  src/mocks/broswer.ts
  src/mocks/data/homeProductsData.ts
  src/mocks/handlers/home.ts
  src/pages/Register.tsx
  src/pages/home.tsx
  src/tests/Home.test.tsx
  src/tests/Register.test.tsx
  tailwind.config.js
Labels: 👩🏻‍💻frontend

#32 test & feat: 입찰
  src/components/bid/BidCaution.tsx
  src/components/bid/queries.ts
  src/components/common/CautionCheck.tsx
  src/components/form/FormField.tsx
  src/components/home/HomeProductItem.tsx
  src/components/queryKeys.ts
  src/components/register/RegisterCaution.tsx
  src/components/register/RegisterLabel.tsx
  src/constants/api.ts
  src/constants/caution.ts
  src/constants/route.ts
  src/constants/schema.ts
  src/mocks/broswer.ts
  src/mocks/handlers/details.ts
  src/pages/Bid.tsx
  src/pages/Register.tsx
  src/routing.tsx
  src/tests/Bid.test.tsx
  src/tests/Home.test.tsx
  src/tests/Register.test.tsx
  src/utils/getTimeColor.ts
Labels: ✨feature, 👩🏻‍💻frontend

#33 Feat: 회원가입 페이지, 로그인 페이지 OAuth, 모든 등록 내역페이지 기능 구현
  public/Nike_RedWhite_Thumbnail.jpeg
  public/kakao_login_large_wide.png
  public/kakao_login_medium_narrow.png
  src/App.tsx
  src/api/auction.api.ts
  src/api/login.api.ts
  src/api/product.api.ts
  src/api/user.api.ts
  src/components/common/Button.tsx
  src/components/common/ProductItem.tsx
  src/components/common/ProductLists.tsx
  src/components/mypage/MyPageOrder.tsx
  src/components/order/OrderProduct.tsx
  src/components/product/OngoingProduct.tsx
  src/components/product/ProductButtons.tsx
  src/components/product/UpcomingProduct.tsx
  src/components/profile/FindAddressButton.tsx
  src/components/profile/ProfileInput.tsx
  src/components/profile/SelectBank.tsx
  src/components/profile/SelectCountry.tsx
  src/constants/api.ts
  src/constants/bank.ts
  src/constants/countries.ts
  src/constants/queryKey.ts
  src/constants/route.ts
  src/constants/schema.ts
  src/hooks/useFilterButtons.ts
  src/hooks/useKakaoInit.ts
  src/hooks/useMyAuction.ts
  src/hooks/useProductList.ts
  src/hooks/useSignup.ts
  src/mocks/broswer.ts
  src/mocks/data/auctionData.ts
  src/mocks/data/ongoingData.ts
  src/mocks/data/upcomingData.ts
  src/mocks/handlers/Login.ts
  src/mocks/handlers/ProductList.ts
  src/mocks/handlers/myAuctuon.ts
  src/pages/AllOrderList.tsx
  src/pages/Login.tsx
  src/pages/MyOrderList.tsx
  src/pages/MyPage.tsx
  src/pages/OrderHistory.tsx
  src/pages/ProductList.tsx
  src/pages/ProfileEdit.tsx
  src/pages/Signup.tsx
  src/routing.tsx
  src/types/kakao.d.ts
  src/types/myAuctionData.d.ts
  src/types/productList.d.ts
  src/types/user.d.ts
  src/types/window.d.ts
  tailwind.config.js
Labels: ✨feature
