Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2024-07, with the labels that each got.

#4 [FE] chore: eslint-airbnb 초기 세팅
  .eslintrc.cjs
  src/App.tsx
  src/main.tsx
Labels: ⚙️chore, 👩🏻‍💻frontend

#9 Feat: UI-Homepage 완성
  .eslintrc.cjs
  package-lock.json
  package.json
  public/air-jordan-row.jpeg
  src/App.tsx
  src/components/CategoryList.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HomeItem.tsx
  src/components/HomeItemList.tsx
  src/components/Layout.tsx
  src/constants/categories.ts
  src/pages/home.tsx
  src/ui/Footer.tsx
  src/ui/Header.tsx
  src/ui/Layout.tsx
Labels: ✨feature

#5 Chore: router, global style (reset) 설정
  .env
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/constant/route.ts
  src/index.css
  src/pages/MainPage.tsx
  src/routing.tsx
  tailwind.config.js
Labels: ⚙️chore, 👩🏻‍💻frontend

#8 Feat: 상품 등록 페이지 마크업 및 Button 공통 컴포넌트 생성
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/ProductList.tsx
  src/components/common/Button.tsx
  src/mock/data/ongoingData.ts
  src/mock/data/upcomingData.ts
Labels: ✨feature, 👩🏻‍💻frontend

#10 Chore: tanstack-query, MSW, 절대 경로 설정
  .eslintrc.cjs
  package-lock.json
  package.json
  src/main.tsx
  src/provider/queryProvider.tsx
  tsconfig.app.json
  tsconfig.base.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙️chore

#17 chore : axios 세팅 msw 연동 및 테스트
  .env
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/api/test.api.ts
  src/constants/api.ts
  src/main.tsx
  src/mocks/broswer.ts
  src/mocks/handlers.ts
  src/mocks/handlers/test.ts
  src/mocks/node.ts
  src/pages/Test.tsx
  src/routing.tsx
  src/utils/axios.ts
  tsconfig.base.json
  vite.config.ts
Labels: ⚙️chore
