Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2025-02, with the labels that each got.

#271 fix: e2e-test 수정
  cypress/e2e/Bid.cy.ts
  cypress/e2e/EndAuction.cy.ts
Labels: 🐛bug

#275 fix: ci-workflow
  .github/workflows/integration-main.yml
  src/app/main.tsx
Labels: ⚙️chore, 👩🏻‍💻frontend

#276 fix: test 전략 수정
  .github/workflows/integration-main.yml
  .github/workflows/integration-test.yml
  cypress/e2e/Notification.cy.ts
  src/app/main.tsx
Labels: 🐛bug

#277 feat: ci workflow 최적화
  .github/workflows/integration-main.yml
Labels: ✨feature, 👩🏻‍💻frontend

#279 fix: CI workflow 수정
  .github/workflows/integration-main.yml
Labels: ✨feature, 👩🏻‍💻frontend

#278 v2.2.8
  .github/workflows/integration-main.yml
Labels: ✨feature, 👩🏻‍💻frontend

#280 refactor: 이미지 최적화
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/features/notification/ui/NotificationItem.tsx
  src/features/user/ui/OrderWonProduct.tsx
  src/pages/payment/ui/Payment.tsx
  src/shared/ui/AuctionItem.tsx
  src/shared/ui/ProductItem.tsx
  src/shared/ui/ProgressiveImage.tsx
  src/shared/ui/index.ts
  src/stories/components/product/ProductItem.test.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#281 refactor: rendering optimization
  package-lock.json
  package.json
  src/app/main.tsx
  src/pages/home/lib/useScrollDetection.ts
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeRegisterBtn.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#285 refactor: 폰트 적용 및 최적화
  package-lock.json
  src/app/index.css
  src/shared/assets/fonts/Pretendard-Black.woff
  src/shared/assets/fonts/Pretendard-Bold.woff2
  src/shared/assets/fonts/Pretendard-ExtraBold.woff
  src/shared/assets/fonts/Pretendard-ExtraLight.woff
  src/shared/assets/fonts/Pretendard-Light.woff
  src/shared/assets/fonts/Pretendard-Medium.woff2
  src/shared/assets/fonts/Pretendard-Regular.woff2
  src/shared/assets/fonts/Pretendard-SemiBold.woff2
  src/shared/assets/fonts/Pretendard-Thin.woff
  tailwind.config.js
Labels: ⚙️chore, ✨feature, 👩🏻‍💻frontend

#286 refactor: code splitting
  package-lock.json
  package.json
  src/app/router.tsx
  src/features/auth/api/postSignup.ts
  src/features/auth/hooks/useAuth.ts
  src/features/auth/index.ts
  src/features/auth/model/useRefreshTokenOnSuccess.ts
  src/features/auth/test/handler.ts
  src/pages/bid/index.ts
  src/pages/bid/ui/Bid.tsx
  src/pages/bid/ui/index.ts
  src/pages/bidder-list/index.ts
  src/pages/bidder-list/ui/BidderList.tsx
  src/pages/bidder-list/ui/index.ts
  src/pages/details/index.ts
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/details/ui/index.ts
  src/pages/edit-auction/index.ts
  src/pages/edit-auction/ui/EditAuction.tsx
  src/pages/edit-auction/ui/index.ts
  src/pages/home/ui/BestItemList.tsx
  src/pages/home/ui/ImminentItemList.tsx
  src/pages/home/ui/PreAuctionItemList.tsx
  src/shared/api/axios.ts
  src/shared/utils/RouteLoader.ts
  src/shared/utils/index.ts
  vite.config.ts
Labels: ✨feature, 👩🏻‍💻frontend

#287 v2.3.0
  package-lock.json
  package.json
  src/app/index.css
  src/app/router.tsx
  src/features/auth/api/postSignup.ts
  src/features/auth/hooks/useAuth.ts
  src/features/auth/index.ts
  src/features/auth/model/useRefreshTokenOnSuccess.ts
  src/features/auth/test/handler.ts
  src/pages/bid/index.ts
  src/pages/bid/ui/Bid.tsx
  src/pages/bid/ui/index.ts
  src/pages/bidder-list/index.ts
  src/pages/bidder-list/ui/BidderList.tsx
  src/pages/bidder-list/ui/index.ts
  src/pages/details/index.ts
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/details/ui/index.ts
  src/pages/edit-auction/index.ts
  src/pages/edit-auction/ui/EditAuction.tsx
  src/pages/edit-auction/ui/index.ts
  src/pages/home/ui/BestItemList.tsx
  src/pages/home/ui/ImminentItemList.tsx
  src/pages/home/ui/PreAuctionItemList.tsx
  src/shared/api/axios.ts
  src/shared/assets/fonts/Pretendard-Black.woff
  src/shared/assets/fonts/Pretendard-Bold.woff2
  src/shared/assets/fonts/Pretendard-ExtraBold.woff
  src/shared/assets/fonts/Pretendard-ExtraLight.woff
  src/shared/assets/fonts/Pretendard-Light.woff
  src/shared/assets/fonts/Pretendard-Medium.woff2
  src/shared/assets/fonts/Pretendard-Regular.woff2
  src/shared/assets/fonts/Pretendard-SemiBold.woff2
  src/shared/assets/fonts/Pretendard-Thin.woff
  src/shared/utils/RouteLoader.ts
  src/shared/utils/index.ts
  tailwind.config.js
  vite.config.ts
Labels: ⚙️chore, ✨feature, 👩🏻‍💻frontend

#288 fix: bundle option 수정
  vite.config.ts
Labels: ⚙️chore

#289 v2.3.1
  vite.config.ts
Labels: ⚙️chore

#290 fix: bundle chunk 수정
  vite.config.ts
Labels: ⚙️chore, 🐛bug

#291 v2.3.2
  vite.config.ts
Labels: ⚙️chore, 🐛bug

#294 refactor: bundle option
  package-lock.json
  vite.config.ts
Labels: ⚙️chore, ✨feature, 🐛bug, 👩🏻‍💻frontend

#297 refactoring: 병합 오류 해결
  src/app/router.tsx
Labels: 🐛bug

#298 refactoring: 렌더링 최적화 및 로그인 코드 수정
  src/entities/address/address.ts
  src/features/address/config/index.ts
  src/features/address/config/schema.ts
  src/features/auth/hooks/useAuth.ts
  src/features/sign-up/test/Signup.test.tsx
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressAdd.tsx
  src/pages/payment/ui/PaymentAddressEdit.tsx
  src/pages/sign-up/Signup.tsx
Labels: 🐛bug, 🪄refactor

#300 fix: LCP 지수 개선
  .github/workflows/integration-main.yml
  src/app/main.tsx
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/shared/ui/ProgressiveImage.tsx
  src/stories/components/product/ProductItem.test.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#302 fix: CI-workflow
  .github/workflows/integration-main.yml
Labels: ⚙️chore, 🐛bug

#304 v2.3.5
  src/app/index.css
Labels: ⚙️chore

#305 fix: login cors
  src/features/auth/hooks/useAuth.ts
  src/shared/ui/AuctionForm.tsx
  src/shared/ui/Button.tsx
  src/stories/components/product/ProductItem.mdx
Labels: ⚙️chore, ✨feature, 🐛bug, 👩🏻‍💻frontend

#307 fix: mode 수정
  src/features/auth/hooks/useAuth.ts
Labels: 🐛bug

#306 v2.3.6
  src/features/auth/hooks/useAuth.ts
  src/shared/ui/AuctionForm.tsx
  src/shared/ui/Button.tsx
  src/stories/components/product/ProductItem.mdx
Labels: ⚙️chore, ✨feature, 🐛bug, 👩🏻‍💻frontend

#309 Bugfix: 사전 경매 버튼 오류수정
  src/features/product-list/ui/PreAuctionProduct.tsx
Labels: 🐛bug

#310 v2.3.7
  index.html
  public/robots.txt
  src/app/layout/ui/Navigation.tsx
  src/features/details/ui/ProgressBar.tsx
  src/features/product-list/ui/PreAuctionProduct.tsx
  src/shared/ui/ProductItem.tsx
  tailwind.config.js
Labels: ⚙️chore, ✨feature, 👩🏻‍💻frontend
