Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2025-01, with the labels that each got.

#236 Refactoring: 닉네임 중복체크 코드 분리
  src/features/profile/hooks/useProfileNicknameValidate.ts
  src/features/sign-up/hooks/useSignupNicknameValidate.ts
  src/features/sign-up/model/signupSlice.ts
  src/pages/sign-up/ui/Signup.tsx
  src/pages/user/ui/UserProfileEdit.tsx
  src/shared/utils/updateProfileEditState.ts
  src/stories/components/auction/AuctionItem.stories.tsx
  src/stories/components/button/Button.stoires.tsx
  src/stories/components/price/Price.stories.tsx
  src/stories/components/product/ProductItem.mdx
  src/stories/components/product/ProductItem.stories.tsx
  src/stories/components/product/ProductItem.test.tsx
  src/stories/components/product/index.ts
Labels: 🪄refactor

#238 Feat: 검색 기능 추가
  package-lock.json
  package.json
  src/app/router.tsx
  src/entities/auction/model/types/item.ts
  src/features/auction-search/api/getAuctionSearch.ts
  src/features/auction-search/api/getPreAuctionSearch.tsx
  src/features/auction-search/api/index.ts
  src/features/auction-search/model/index.ts
  src/features/auction-search/model/useGetAuctionSearch.ts
  src/pages/Test.tsx
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeSearchBar.tsx
  src/pages/search/index.ts
  src/pages/search/ui/AuctionSearch.tsx
  src/pages/search/ui/AuctionSearchItem.tsx
  src/pages/search/ui/PreAuctionSearchItem.tsx
  src/pages/search/ui/index.ts
  src/shared/constants/apiEndPoint.ts
  src/shared/constants/routes.ts
  src/shared/ui/Command.tsx
  src/shared/ui/Dialog.tsx
  src/shared/ui/TimeRemaining.tsx
  src/shared/ui/index.ts
Labels: ✨feature

#237 Refactor/upload image
  .dockerignore
  index.html
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/app/layout/ui/Navigation.tsx
  src/app/main.tsx
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/features/register/api/index.ts
  src/features/register/index.ts
  src/features/register/lib/imageCompressionWorker.ts
  src/features/register/lib/index.ts
  src/features/register/lib/useDragAndDrop.ts
  src/features/register/lib/useImageUploader.ts
  src/features/register/ui/AddImageButton.tsx
  src/features/register/ui/ImageItem.tsx
  src/features/register/ui/ImageOverlay.tsx
  src/features/register/ui/ImageUploader.tsx
  src/features/register/ui/ImageUploaderInput.tsx
  src/features/register/ui/index.ts
  src/features/register/utils/compressAndConvertToWebp.ts
  src/features/register/utils/convertDataURLtoFile.ts
  src/features/register/utils/index.ts
  src/pages/home/ui/BestItemList.tsx
  src/pages/home/ui/ImminentItemList.tsx
  src/pages/home/ui/PreAuctionItemList.tsx
  src/shared/ui/AuctionForm.tsx
  src/shared/ui/AuctionItem.tsx
  src/shared/ui/ProgressCircle.tsx
  src/shared/ui/index.ts
Labels: ✨feature, 👩🏻‍💻frontend

#241 Fix: 검색 스타일 수정
  src/features/auction-search/model/index.ts
  src/features/auction-search/model/useGetAuctionSearch.ts
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeSearchBar.tsx
  src/pages/search/ui/AuctionSearch.tsx
  src/shared/ui/Command.tsx
Labels: ✨feature

#242 style: 검색 스타일 수정
  src/app/layout/ui/Layout.tsx
  src/app/layout/ui/LayoutWithNav.tsx
  src/app/router.tsx
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeSearchBar.tsx
  src/pages/search/ui/AuctionSearch.tsx
  src/shared/ui/Command.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#244 Fix: drag and drop
  src/features/register/lib/useDragAndDrop.ts
  src/features/register/ui/ImageUploaderInput.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#245 v2.2.1
  src/features/register/lib/useDragAndDrop.ts
  src/features/register/ui/ImageUploaderInput.tsx
Labels: 🐛bug

#246 Fix: 스타일 변경 및 preconnect 수정
  index.html
  src/pages/home/ui/PreAuctionItemList.tsx
  src/shared/ui/AuctionItem.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#247 v2.2.2
  index.html
  src/pages/home/ui/PreAuctionItemList.tsx
  src/shared/ui/AuctionItem.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#248 Fix: preconnect 수정
  index.html
Labels: ✨feature, 👩🏻‍💻frontend

#252 refactor: error-boundary
  src/app/App.tsx
  src/app/layout/ui/GlobalLayout.tsx
  src/app/layout/ui/Layout.tsx
  src/app/provider/queryProvider.tsx
  src/app/router.tsx
  src/features/notification/ui/NotificationItem.tsx
  src/pages/bid/ui/Bid.tsx
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/home/ui/CategoryList.tsx
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeItemField.tsx
  src/pages/home/ui/HomeSearchBar.tsx
  src/pages/search/ui/AuctionSearch.tsx
  src/pages/settlement/ui/Settlement.tsx
  src/shared/ui/boundary/APIAsyncBoundary.tsx
  src/shared/ui/boundary/AsyncBoundary.tsx
  src/shared/ui/boundary/EmptyBoundary.tsx
  src/shared/ui/boundary/GlobalAsyncBoundary.tsx
  src/shared/ui/boundary/LocalAPIAsyncBoundary.tsx
  src/shared/ui/boundary/PartialAsyncBoundary.tsx
  src/shared/ui/boundary/RouteErrorFallback.tsx
  src/shared/ui/boundary/index.ts
  src/shared/ui/index.ts
  src/shared/ui/spinner/GlobalSpinner.tsx
  src/shared/ui/spinner/LocalSpinner.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#254 v2.2.4
  src/app/App.tsx
  src/app/layout/ui/GlobalLayout.tsx
  src/app/layout/ui/Layout.tsx
  src/app/provider/queryProvider.tsx
  src/app/router.tsx
  src/features/notification/ui/NotificationItem.tsx
  src/pages/bid/ui/Bid.tsx
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/home/ui/CategoryList.tsx
  src/pages/home/ui/Home.tsx
  src/pages/home/ui/HomeItemField.tsx
  src/pages/home/ui/HomeSearchBar.tsx
  src/pages/search/ui/AuctionSearch.tsx
  src/pages/settlement/ui/Settlement.tsx
  src/shared/ui/boundary/APIAsyncBoundary.tsx
  src/shared/ui/boundary/AsyncBoundary.tsx
  src/shared/ui/boundary/EmptyBoundary.tsx
  src/shared/ui/boundary/GlobalAsyncBoundary.tsx
  src/shared/ui/boundary/LocalAPIAsyncBoundary.tsx
  src/shared/ui/boundary/PartialAsyncBoundary.tsx
  src/shared/ui/boundary/RouteErrorFallback.tsx
  src/shared/ui/boundary/index.ts
  src/shared/ui/index.ts
  src/shared/ui/spinner/GlobalSpinner.tsx
  src/shared/ui/spinner/LocalSpinner.tsx
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup

#255 style: boundary 스타일 수정
  src/features/bid/ui/BidForm.tsx
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/pages/bid/ui/Bid.tsx
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/settlement/ui/Settlement.tsx
  src/pages/settlement/ui/SettlementMain.tsx
Labels: 🧹cleanup

#256 v2.2.4
  src/features/bid/ui/BidForm.tsx
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/pages/bid/ui/Bid.tsx
  src/pages/details/ui/AuctionDetails.tsx
  src/pages/details/ui/PreAuctionDetails.tsx
  src/pages/settlement/ui/Settlement.tsx
  src/pages/settlement/ui/SettlementMain.tsx
Labels: 🧹cleanup

#253 Feat: 테스트 코드 수정 및 추가
  package-lock.json
  package.json
  src/features/address/test/Address.test.tsx
  src/features/auction-search/api/index.ts
  src/features/auction-search/test/AuctionSearch.test.tsx
  src/features/auth/test/Login.test.tsx
  src/features/product-list/test/ProductList.test.tsx
  src/features/profile/test/ProfileEdit.test.tsx
  src/features/sign-up/hooks/useSignupNicknameValidate.ts
  src/features/sign-up/test/Signup.test.tsx
  src/features/user/test/User.test.tsx
  src/features/user/test/UserParticipatedList.test.tsx
  src/features/user/test/UserRegisteredList.test.tsx
  src/features/user/ui/UserProfile.tsx
  src/shared/utils/formatCurrencyWithWon.ts
Labels: ✨feature

#259 fix: 테스트 에러 수정
  src/features/product-list/test/ProductList.test.tsx
  src/features/profile/test/ProfileEdit.test.tsx
  src/features/sign-up/test/Signup.test.tsx
  src/features/user/test/User.test.tsx
  src/features/user/test/UserParticipatedList.test.tsx
  src/features/user/test/UserRegisteredList.test.tsx
Labels: 🐛bug

#260 v.2.2.5
  src/features/product-list/test/ProductList.test.tsx
  src/features/profile/test/ProfileEdit.test.tsx
  src/features/sign-up/test/Signup.test.tsx
  src/features/user/test/User.test.tsx
  src/features/user/test/UserParticipatedList.test.tsx
  src/features/user/test/UserRegisteredList.test.tsx
Labels: 🐛bug

#261 fix: build error
  index.html
  src/features/details/test/data.ts
  src/features/heart/test/data.ts
  src/features/notification/test/data.ts
  src/pages/home/test/data.ts
  src/shared/assets/index.ts
  src/shared/assets/test/index.ts
  src/shared/index.ts
  vite.config.ts
Labels: 🐛bug

#262 fix: 테스트 용 이미지 경로 수정
  src/features/details/test/data.ts
  src/features/heart/test/data.ts
  src/features/notification/test/data.ts
  src/pages/home/test/data.ts
Labels: 🐛bug

#264 refactoring: 로그인 테스트 모킹 추가
  .eslintrc.cjs
  .gitignore
  .prettierrc
  package-lock.json
  src/entities/address/index.ts
  src/features/address/test/Address.test.tsx
  src/features/address/test/mockData.ts
  src/features/auth/test/Login.test.tsx
  src/features/auth/test/handler.ts
  src/features/auth/test/index.ts
  src/features/product-list/test/handler.ts
  src/features/product-list/test/index.ts
  src/features/product-list/test/ongoingData.ts
  src/features/user/test/auctionData.ts
  src/features/user/test/handler.ts
  src/features/user/test/index.ts
  src/features/user/test/preEnrollData.ts
  src/shared/api/msw/browser.ts
Labels: 👩🏻‍💻frontend

#265 fix: 테스트 이미지 빌드 설정 수정
  vite.config.ts
Labels: ✨feature, 🐛bug

#266 Refactoring: 로그인 모킹 코드 수정
  src/features/auth/hooks/useAuth.ts
  src/features/auth/test/handler.ts
  src/features/product-list/test/handler.ts
  src/features/user/test/handler.ts
  src/shared/api/msw/browser.ts
Labels: ✨feature

#267 Refactor: generics
  src/features/auth/index.ts
  src/features/auth/test/handler.ts
  src/features/auth/test/index.ts
  src/features/bid/test/Bid.test.tsx
  src/features/bid/ui/BidForm.tsx
  src/features/details/api/getAuctionDetails.ts
  src/features/details/api/getPreAuctionDetails.ts
  src/features/details/api/index.ts
  src/features/details/index.ts
  src/features/details/model/index.ts
  src/features/details/model/useGetAuctionDetails.ts
  src/features/details/model/useGetPreAuctionDetails.ts
  src/features/details/model/useToggleAuctionDetailsHeart.ts
  src/features/details/test/AuctionDetails.test.tsx
  src/features/details/test/PreAuctionDetails.test.tsx
  src/features/details/ui/AuctionDetailsFooter.tsx
  src/features/details/ui/AuctionDetailsMain.tsx
  src/features/details/ui/PreAuctionDetailsMain.tsx
  src/features/heart/model/useDeleteHeart.ts
  src/features/product-list/index.ts
  src/features/product-list/model/useToggleAuctionListHeart.ts
  src/features/product-list/test/handler.ts
  src/features/product-list/test/index.ts
  src/features/user/index.ts
  src/features/user/test/handler.ts
  src/features/user/test/index.ts
  src/pages/bidder-list/test/BidderList.test.tsx
  src/pages/bidder-list/ui/BidderListMain.tsx
  src/pages/edit-auction/ui/EditAuction.tsx
  src/shared/api/msw/browser.ts
  src/shared/constants/queryKeys.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🧹cleanup
