Repository JECT-Study/Chzz-Market-Frontend, pull requests merged in 2025-03, with the labels that each got.

#311 refactoring: 로그인 필요한 api만 에러핸들링
  src/features/auth/hooks/useAuth.ts
  src/shared/api/axios.ts
  src/shared/constants/apiEndPoint.ts
Labels: 🪄refactor

#312 refactoring: 로그인 성공 시 경로 수정
  src/features/auth/model/useRefreshTokenOnSuccess.ts
  src/features/auth/test/Login.test.tsx
  src/pages/home/test/Home.test.tsx
  src/pages/home/ui/Home.tsx
  src/pages/login/Login.tsx
Labels: 🪄refactor

#313 v2.3.8
  src/features/auth/hooks/useAuth.ts
  src/features/auth/model/useRefreshTokenOnSuccess.ts
  src/features/auth/test/Login.test.tsx
  src/pages/home/test/Home.test.tsx
  src/pages/home/ui/Home.tsx
  src/pages/login/Login.tsx
  src/shared/api/axios.ts
  src/shared/constants/apiEndPoint.ts
Labels: ✨feature, 👩🏻‍💻frontend

#315 v2.3.9
  src/features/details/test/PreAuctionDetails.test.tsx
  src/features/details/ui/PreAuctionDetailsFooter.tsx
  src/features/notification/ui/NotificationItem.tsx
  src/features/user/ui/OrderWonProduct.tsx
  src/pages/payment/ui/Payment.tsx
  src/shared/ui/AuctionItem.tsx
  src/shared/ui/ProductItem.tsx
  src/shared/ui/ProgressiveImage.tsx
  src/stories/components/product/ProductItem.test.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#318 feat: deploy cache 전략 추가
  .github/workflows/deploy.yml
Labels: ✨feature, 👩🏻‍💻frontend

#319 fix: matrix 삭제
  .github/workflows/integration-main.yml
Labels: ⚙️chore

#320 fix: 오타 수정
  .github/workflows/deploy.yml
Labels: 🐛bug

#321 v2.3.11
  .github/workflows/deploy.yml
Labels: 🐛bug

#322 feat: preconnect
  index.html
Labels: ⚙️chore, ✨feature, 👩🏻‍💻frontend

#323 v2.3.12
  index.html
Labels: ✨feature, 👩🏻‍💻frontend

#324 fix: preconnect 수정
  index.html
Labels: ✨feature, 👩🏻‍💻frontend

#325 v2.3.13
  index.html
Labels: ✨feature, 👩🏻‍💻frontend

#326 Bugfix: axios apis 이전 코드로 수정 및 리드미 파일 수정
  README.md
  src/shared/api/axios.ts
  src/shared/constants/apiEndPoint.ts
Labels: 📃docs

#327 fix: icon-style
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#328 v2.3.14
  README.md
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/shared/api/axios.ts
  src/shared/constants/apiEndPoint.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#330 fix: useSSE 수정
  src/features/notification/model/useSSE.ts
  src/shared/ui/ErrorMessage.tsx
  src/shared/ui/boundary/AsyncBoundary.tsx
  src/shared/ui/boundary/GlobalAsyncBoundary.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#331 v2.3.15
  src/features/notification/model/useSSE.ts
  src/shared/ui/ErrorMessage.tsx
  src/shared/ui/boundary/AsyncBoundary.tsx
  src/shared/ui/boundary/GlobalAsyncBoundary.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#332 feat: rollback workflow 작성
  .github/workflows/deploy.yml
  .github/workflows/rollback.yml
Labels: ⚙️chore, ✨feature, 👩🏻‍💻frontend

#329 refactoring: icon 사이즈 변경
  README.md
  src/features/user/ui/EndMyRegister.tsx
  src/features/user/ui/OrderWonProduct.tsx
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/shared/constants/apiEndPoint.ts
  src/shared/ui/CreatedAt.tsx
Labels: 📃docs

#333 v2.3.16
  .github/workflows/deploy.yml
  .github/workflows/rollback.yml
  README.md
  src/features/user/ui/EndMyRegister.tsx
  src/features/user/ui/OrderWonProduct.tsx
  src/pages/payment/ui/Payment.tsx
  src/pages/payment/ui/PaymentAddressEditList.tsx
  src/pages/payment/ui/PaymentAddressList.tsx
  src/shared/constants/apiEndPoint.ts
  src/shared/ui/CreatedAt.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend, 📃docs

#334 fix: innerHeight를 visualViewport로 변경
  src/app/App.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#335 v2.3.17
  src/app/App.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#336 refactoring: axios 로그인 필요 코드 수정
  src/shared/api/axios.ts
Labels: 🪄refactor

#337 v2.3.18
  src/shared/api/axios.ts
Labels: 🐛bug, 👩🏻‍💻frontend

#338 Refactoring: 토큰 만료시 페이지 강제이동 삭제
  src/shared/api/axios.ts
Labels: 🪄refactor
